name: Dockerized CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Create .env file for backend
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> backend/.env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> backend/.env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

      
      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chatapp-backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chatapp-frontend:latest ./frontend

      
      - name: Run Containers
        run: docker-compose up -d

      - name: Wait for services to stabilize
        run: sleep 15

      - name: Check running containers
        run: docker ps

      - name: Stop Containers
        run: docker-compose down

      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatapp-backend:latest

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chatapp-frontend:latest
